import type { Endpoint } from "./registry.js";

// Read-only (GET) endpoints taken from https://www.zoho.com/books/api/v3/ .
// Purchases, accounting, banking and settings. Sales modules live in endpoints-sales.ts.

const dates = ["date", "date_start", "date_end", "date_before", "date_after"];
const common = ["search_text", "filter_by", "sort_column", "sort_order"];

export const coreEndpoints: Endpoint[] = [
  // ---- organizations ----
  { name: "list_organizations", description: "List every Zoho Books organization (client company) this connector can use, with its organization_id. Pass an organization name or id as `organization` to any other function.", path: "/organizations" },
  { name: "get_organization", description: "Get one organization by organization_id.", path: "/organizations/{organization_id}" },
  { name: "list_organizations_for_user", description: "List organizations the current user belongs to.", path: "/organizations/user" },
  { name: "get_organization_address", description: "Get the organization's address(es).", path: "/organizations/address" },

  // ---- expenses ----
  { name: "list_expenses", description: "List expenses.", path: "/expenses", paginated: true,
    filters: [...dates, "description", "reference_number", "status", "amount", "account_name", "customer_name", "vendor_name", "customer_id", "vendor_id", "recurring_expense_id", "paid_through_account_id", "project_id", ...common] },
  { name: "get_expense", description: "Get an expense by expense_id.", path: "/expenses/{expense_id}" },
  { name: "list_expense_comments", description: "List an expense's history and comments.", path: "/expenses/{expense_id}/comments" },
  { name: "list_employees", description: "List employees.", path: "/employees", paginated: true },
  { name: "list_recurring_expenses", description: "List recurring expenses.", path: "/recurringexpenses", paginated: true,
    filters: ["recurrence_name", "status", "account_id", "account_name", "amount", "customer_name", "customer_id", "paid_through_account_id", "last_created_date", "next_expense_date", ...common] },
  { name: "get_recurring_expense", description: "Get a recurring expense by recurring_expense_id.", path: "/recurringexpenses/{recurring_expense_id}" },
  { name: "list_recurring_expense_children", description: "List expenses generated by a recurring expense.", path: "/recurringexpenses/{recurring_expense_id}/expenses", paginated: true, filters: ["sort_column"] },
  { name: "list_recurring_expense_comments", description: "List a recurring expense's history and comments.", path: "/recurringexpenses/{recurring_expense_id}/comments" },

  // ---- purchase orders / returns ----
  { name: "list_purchase_orders", description: "List purchase orders.", path: "/purchaseorders", paginated: true,
    filters: [...dates, "purchaseorder_number", "reference_number", "status", "item_name", "item_description", "vendor_name", "total", "vendor_id", "item_id", "last_modified_time", "location_ids", ...common] },
  { name: "get_purchase_order", description: "Get a purchase order by purchaseorder_id, including line items.", path: "/purchaseorders/{purchaseorder_id}", fixed: { accept: "json" } },
  { name: "get_purchase_order_email", description: "Get the email content for a purchase order.", path: "/purchaseorders/{purchaseorder_id}/email", filters: ["email_template_id"] },
  { name: "list_purchase_order_templates", description: "List purchase order templates.", path: "/purchaseorders/templates" },
  { name: "list_purchase_order_comments", description: "List a purchase order's history and comments.", path: "/purchaseorders/{purchaseorder_id}/comments" },
  { name: "list_purchase_returns", description: "List purchase returns.", path: "/purchasereturns", paginated: true,
    filters: ["status", "vendor_name", "purchasereturn_number", "purchaseorder_number", "purchasereturn_date", "item_name", "customview_id", ...common] },
  { name: "get_purchase_return", description: "Get a purchase return by purchase_return_id.", path: "/purchasereturns/{purchase_return_id}" },

  // ---- bills ----
  { name: "list_bills", description: "List bills.", path: "/bills", paginated: true,
    filters: [...dates, "bill_number", "reference_number", "due_date", "status", "description", "vendor_name", "total", "vendor_id", "project_id", "item_name", "item_id", "recurring_bill_id", "purchaseorder_id", "customer_id", "last_modified_time", "location_ids", ...common] },
  { name: "get_bill", description: "Get a bill by bill_id, including line items.", path: "/bills/{bill_id}" },
  { name: "list_bill_payments", description: "List payments applied to a bill.", path: "/bills/{bill_id}/payments" },
  { name: "list_bill_comments", description: "List a bill's history and comments.", path: "/bills/{bill_id}/comments" },
  { name: "get_bill_from_purchase_orders", description: "Preview a bill pre-filled from purchase orders (read-only; nothing is created).", path: "/bills/editpage/frompurchaseorders", filters: ["purchaseorder_ids"] },
  { name: "list_recurring_bills", description: "List recurring bills.", path: "/recurringbills",
    filters: ["recurring_bill_id", "vendor_id", "vendor_name", "status", "recurrence_name", "start_date", "end_date"] },
  { name: "get_recurring_bill", description: "Get a recurring bill by recurring_bill_id.", path: "/recurringbills/{recurring_bill_id}" },
  { name: "list_recurring_bill_comments", description: "List a recurring bill's history and comments.", path: "/recurringbills/{recurring_bill_id}/comments" },

  // ---- vendor credits / payments ----
  { name: "list_vendor_credits", description: "List vendor credits.", path: "/vendorcredits", paginated: true,
    filters: [...dates, "vendor_credit_number", "status", "total", "reference_number", "customer_name", "item_name", "notes", "last_modified_time", "customer_id", "item_id", "tax_id", "location_ids", ...common] },
  { name: "get_vendor_credit", description: "Get a vendor credit by vendor_credit_id.", path: "/vendorcredits/{vendor_credit_id}", fixed: { accept: "json" } },
  { name: "list_vendor_credit_bills", description: "List bills a vendor credit was applied to.", path: "/vendorcredits/{vendor_credit_id}/bills" },
  { name: "list_vendor_credit_refunds", description: "List refunds of a vendor credit.", path: "/vendorcredits/{vendor_credit_id}/refunds", paginated: true },
  { name: "get_vendor_credit_refund", description: "Get one refund of a vendor credit.", path: "/vendorcredits/{vendor_credit_id}/refunds/{vendor_credit_refund_id}" },
  { name: "list_all_vendor_credit_refunds", description: "List refunds across all vendor credits.", path: "/vendorcredits/refunds", paginated: true, filters: ["customer_id", "last_modified_time", "sort_column"] },
  { name: "list_vendor_credit_comments", description: "List a vendor credit's history and comments.", path: "/vendorcredits/{vendor_credit_id}/comments" },
  { name: "list_vendor_payments", description: "List vendor payments.", path: "/vendorpayments", paginated: true,
    filters: [...dates, "vendor_name", "reference_number", "payment_number", "amount", "payment_mode", "notes", "vendor_id", "last_modified_time", "bill_id", "description", ...common] },
  { name: "get_vendor_payment", description: "Get a vendor payment by payment_id.", path: "/vendorpayments/{payment_id}", filters: ["fetchTaxInfo", "fetchstatementlineinfo", "is_bill_payment_id"] },
  { name: "list_vendor_payment_refunds", description: "List refunds of a vendor payment.", path: "/vendorpayments/{payment_id}/refunds", paginated: true },
  { name: "get_vendor_payment_refund", description: "Get one refund of a vendor payment.", path: "/vendorpayments/{payment_id}/refunds/{vendorpayment_refund_id}" },
  { name: "get_vendor_payment_email", description: "Get the email content for a vendor payment.", path: "/vendorpayments/{payment_id}/email" },

  // ---- custom modules ----
  { name: "list_custom_modules", description: "List custom modules defined in the organization.", path: "/settings/modules", paginated: true, filters: ["portal_type", "sort_order"] },
  { name: "get_custom_module", description: "Get a custom module's definition by module_api_name (e.g. cm_debtor).", path: "/settings/modules/{module_api_name}" },

  // ---- bank accounts ----
  { name: "list_bank_accounts", description: "List bank and credit card accounts.", path: "/bankaccounts", paginated: true, filters: ["filter_by", "sort_column"] },
  { name: "get_bank_account", description: "Get a bank account by account_id.", path: "/bankaccounts/{account_id}" },
  { name: "list_bank_account_balances", description: "List balances of all bank accounts.", path: "/bankaccounts/balances" },
  { name: "get_bank_accounts_overview", description: "Overview of all bank accounts.", path: "/bankaccounts/overview" },
  { name: "get_bank_account_balance", description: "Balance of one bank account.", path: "/bankaccounts/{account_id}/balance" },
  { name: "get_bank_account_balance_breakdown", description: "Balance breakdown of one bank account.", path: "/bankaccounts/{account_id}/balances" },
  { name: "get_bank_account_overview", description: "Overview of one bank account.", path: "/bankaccounts/{account_id}/overview" },
  { name: "get_bank_statement_summary", description: "Statement summary for a bank account.", path: "/bankaccounts/{account_id}/statementsummary" },
  { name: "get_last_imported_statement", description: "Last imported statement of a bank account.", path: "/bankaccounts/{account_id}/statement/lastimported" },
  { name: "list_bank_statements", description: "List imported statements of a bank account.", path: "/bankaccounts/{account_id}/statements" },
  { name: "list_unreviewed_statement_transactions", description: "List unreviewed statement transactions of a bank account.", path: "/bankaccounts/{account_id}/statements/unreviewed" },
  { name: "list_bank_account_transactions", description: "List transactions of a bank account.", path: "/bankaccounts/{account_id}/transactions" },
  { name: "list_bank_account_subaccounts", description: "List sub-accounts of a bank account.", path: "/bankaccounts/{account_id}/subaccounts" },
  { name: "list_bank_reconciliations", description: "List reconciliations of a bank account.", path: "/bankaccounts/{account_id}/reconciliations" },
  { name: "get_bank_reconciliation", description: "Get one bank reconciliation.", path: "/bankaccounts/{account_id}/reconciliations/{reconciliation_id}" },
  { name: "get_bank_account_preferences", description: "Get a bank account's preferences.", path: "/bankaccounts/{account_id}/preferences" },
  { name: "list_bank_transactions", description: "List banking transactions.", path: "/banktransactions", paginated: true,
    filters: ["account_id", "transaction_type", "date_start", "date_end", "amount_start", "amount_end", "status", "reference_number", "filter_by", "sort_column", "transaction_status", "search_text"] },
  { name: "get_bank_transaction", description: "Get a bank transaction by bank_transaction_id.", path: "/banktransactions/{bank_transaction_id}" },
  { name: "list_matching_transactions", description: "List transactions that could match an uncategorized bank transaction.", path: "/banktransactions/uncategorized/{transaction_id}/match", paginated: true,
    filters: ["transaction_type", "date_after", "date_before", "amount_start", "amount_end", "contact", "reference_number", "show_all_transactions"] },
  { name: "list_bank_rules", description: "List bank rules.", path: "/bankaccounts/rules" },
  { name: "get_bank_rule", description: "Get a bank rule by rule_id.", path: "/bankaccounts/rules/{rule_id}" },
  { name: "list_bank_match_filters", description: "List match filters used by bank rules for the bank account_id (required).", path: "/bankaccounts/matchfilters", filters: ["account_id"] },

  // ---- chart of accounts / registers ----
  { name: "list_chart_of_accounts", description: "List the chart of accounts.", path: "/chartofaccounts", paginated: true,
    filters: ["showbalance", "filter_by", "sort_column", "last_modified_time", "customview_id", "account_id", "account_code", "account_name", "search_text"] },
  { name: "get_chart_account", description: "Get an account from the chart of accounts.", path: "/chartofaccounts/{account_id}" },
  { name: "list_account_transactions", description: "List transactions posted to an account (account_id required).", path: "/chartofaccounts/accounttransactions", paginated: true,
    filters: ["account_id", ...dates, "amount", "amount_less_than", "amount_greater_than", "filter_by", "transaction_type", "sort_column"] },
  { name: "list_register_transactions", description: "Account register (ledger-style) transactions for an account.", path: "/registers/{account_id}/transactions", paginated: true,
    filters: ["filter_by", "from_date", "to_date", "cash_based", "group_by", "sort_column", "optional_columns", "show_fcy"] },
  { name: "get_register_budget_vs_actuals", description: "Budget vs actuals for an account register.", path: "/registers/{account_id}/budgetvsactuals",
    filters: ["budget_id", "filter_by", "cash_based", "from_date", "to_date", "period"] },

  // ---- journals ----
  { name: "list_journals", description: "List manual journals.", path: "/journals", paginated: true,
    filters: [...dates, "entry_number", "reference_number", "notes", "last_modified_time", "total", "customer_id", "vendor_id", "status", "journal_type", "account_id", "account_code", "customview_id", "journal_ids", "currency", "tax_id", "project_id", "location_ids", ...common] },
  { name: "get_journal", description: "Get a journal by journal_id.", path: "/journals/{journal_id}" },
  { name: "list_journal_credits", description: "List available credits of a journal.", path: "/journals/{journal_id}/credits" },
  { name: "list_recurring_journals", description: "List recurring journals.", path: "/recurringjournals", filters: ["filter_by", "sort_column", "account_id"] },
  { name: "get_recurring_journal", description: "Get a recurring journal.", path: "/recurringjournals/{recurring_journal_id}" },
  { name: "list_recurring_journal_children", description: "List journals created from a recurring journal.", path: "/recurringjournals/{recurring_journal_id}/journals" },
  { name: "get_transaction_journal", description: "Journal (ledger) view of a transaction; entity_type is required (invoice, bill, expense, ...).", path: "/transactions/{transaction_id}/journals", filters: ["entity_type", "report_basis"] },

  // ---- fixed assets ----
  { name: "list_fixed_assets", description: "List fixed assets.", path: "/fixedassets", paginated: true, filters: ["filter_by", "sort_column", "sort_order"] },
  { name: "get_fixed_asset", description: "Get a fixed asset by fixed_asset_id.", path: "/fixedassets/{fixed_asset_id}" },
  { name: "get_fixed_asset_history", description: "History of a fixed asset from acquisition to write-off.", path: "/fixedassets/{fixed_asset_id}/history", paginated: true },
  { name: "get_fixed_asset_forecast", description: "Forecast depreciation of a fixed asset.", path: "/fixedassets/{fixed_asset_id}/forecast" },
  { name: "list_fixed_asset_types", description: "List fixed asset types.", path: "/fixedassettypes", paginated: true },

  // ---- currency / adjustments / opening balances / locks / taxes ----
  { name: "list_base_currency_adjustments", description: "List base currency adjustments.", path: "/basecurrencyadjustment", paginated: true, filters: ["filter_by", "sort_column", "last_modified_time"] },
  { name: "get_base_currency_adjustment", description: "Get a base currency adjustment.", path: "/basecurrencyadjustment/{base_currency_adjustment_id}" },
  { name: "get_opening_balance", description: "Get the organization's opening balance.", path: "/settings/openingbalances" },
  { name: "get_opening_balance_details", description: "Opening balance details for an account (account_id required).", path: "/settings/openingbalancedetails", filters: ["account_id"] },
  { name: "list_transaction_locks", description: "List transaction locks.", path: "/transactionlocks", paginated: true, filters: ["accounting_period_id", "lock_scope"] },
  { name: "get_transaction_lock", description: "Get transaction lock details.", path: "/transactionlock", filters: ["accounting_period_id", "transaction_lock_id"] },
  { name: "list_taxes", description: "List taxes (simple and compound).", path: "/settings/taxes", paginated: true },
  { name: "get_tax", description: "Get a tax by tax_id.", path: "/settings/taxes/{tax_id}" },
  { name: "get_tax_group", description: "Get a tax group by tax_group_id.", path: "/settings/taxgroups/{tax_group_id}" },
  { name: "list_tax_authorities", description: "List tax authorities (US edition).", path: "/settings/taxauthorities" },
  { name: "get_tax_authority", description: "Get a tax authority (US and CA editions).", path: "/settings/taxauthorities/{tax_authority_id}" },
  { name: "list_tax_exemptions", description: "List tax exemptions (US edition).", path: "/settings/taxexemptions" },
  { name: "get_tax_exemption", description: "Get a tax exemption (US edition).", path: "/settings/taxexemptions/{tax_exemption_id}" },
  { name: "list_currencies", description: "List currencies.", path: "/settings/currencies", paginated: true, filters: ["filter_by"] },
  { name: "get_currency", description: "Get a currency by currency_id.", path: "/settings/currencies/{currency_id}" },
  { name: "list_exchange_rates", description: "List exchange rates of a currency.", path: "/settings/currencies/{currency_id}/exchangerates", filters: ["from_date", "is_current_date", "sort_column"] },
  { name: "get_exchange_rate", description: "Get one exchange rate.", path: "/settings/currencies/{currency_id}/exchangerates/{exchange_rate_id}" },

  // ---- projects / tasks / time ----
  { name: "list_projects", description: "List projects.", path: "/projects", paginated: true, filters: ["filter_by", "customer_id", "search_text", "sort_column"] },
  { name: "get_project", description: "Get a project by project_id.", path: "/projects/{project_id}" },
  { name: "list_project_users", description: "List users assigned to a project.", path: "/projects/{project_id}/users" },
  { name: "get_project_user", description: "Get a project user.", path: "/projects/{project_id}/users/{user_id}" },
  { name: "list_project_comments", description: "List a project's comments.", path: "/projects/{project_id}/comments" },
  { name: "list_project_invoices", description: "List invoices of a project.", path: "/projects/{project_id}/invoices" },
  { name: "list_project_tasks", description: "List tasks of a project.", path: "/projects/{project_id}/tasks" },
  { name: "get_project_task", description: "Get a project task.", path: "/projects/{project_id}/tasks/{task_id}" },
  { name: "list_tasks", description: "List tasks.", path: "/tasks" },
  { name: "get_task", description: "Get a task by task_id.", path: "/tasks/{task_id}" },
  { name: "list_task_comments", description: "List comments of a task.", path: "/tasks/{task_id}/comments" },
  { name: "list_time_entries", description: "List project time entries.", path: "/projects/timeentries", paginated: true, filters: ["from_date", "to_date", "filter_by", "project_id", "user_id", "sort_column"] },
  { name: "get_time_entry", description: "Get a time entry.", path: "/projects/timeentries/{time_entry_id}" },
  { name: "get_running_timer", description: "Get the current user's running timer.", path: "/projects/timeentries/runningtimer/me" },

  // ---- users / items / pricing / locations / tags ----
  { name: "list_users", description: "List users of the organization.", path: "/users", paginated: true, filters: ["filter_by", "sort_column"] },
  { name: "get_user", description: "Get a user by user_id.", path: "/users/{user_id}" },
  { name: "get_current_user", description: "Get the user the connector is authorized as.", path: "/users/me" },
  { name: "list_items", description: "List items.", path: "/items", paginated: true,
    filters: ["name", "sku", "description", "rate", "tax_id", "item_type", "product_type", "category_id", "location_id", ...common] },
  { name: "get_item", description: "Get an item by item_id.", path: "/items/{item_id}" },
  { name: "list_item_masters", description: "List item masters.", path: "/itemmasters", paginated: true },
  { name: "get_item_master", description: "Get an item master.", path: "/itemmasters/{item_master_id}" },
  { name: "list_item_variants", description: "List item variants.", path: "/itemvariants", paginated: true },
  { name: "get_item_variant", description: "Get an item variant.", path: "/itemvariants/{variant_id}" },
  { name: "list_categories", description: "List item categories.", path: "/categories", paginated: true,
    filters: ["parent_category_id", "include_parent_category", "include_root_category", "last_modified_time", "search_text", "category_ids", "name", "filter_by", "sort_column", "sort_order"] },
  { name: "get_category", description: "Get an item category.", path: "/categories/{category_id}" },
  { name: "list_price_lists", description: "List price lists.", path: "/pricebooks", paginated: true, filters: ["filter_by", "search_text"] },
  { name: "list_price_list_items", description: "List items in a price list (pricebook_id required).", path: "/pricebooks/items", paginated: true, filters: ["pricebook_id"] },
  { name: "list_locations", description: "List business locations.", path: "/locations" },
  { name: "list_reporting_tags", description: "List reporting tags.", path: "/reportingtags" },
  { name: "list_reporting_tag_options", description: "List all options of a reporting tag.", path: "/reportingtags/{tag_id}/options/all" },
];
