import type { Endpoint } from "./registry.js";

// Read-only (GET) endpoints for the sales side, taken from https://www.zoho.com/books/api/v3/ .

const dates = ["date", "date_start", "date_end", "date_before", "date_after"];
const common = ["search_text", "filter_by", "sort_column", "sort_order"];

export const salesEndpoints: Endpoint[] = [
  // ---- contacts ----
  { name: "list_contacts", description: "List customers and vendors.", path: "/contacts", paginated: true,
    filters: ["contact_type", "contact_name", "company_name", "first_name", "last_name", "address", "email", "phone", "zcrm_contact_id", "zcrm_account_id", "zcrm_vendor_id", ...common] },
  { name: "get_contact", description: "Get a contact by contact_id.", path: "/contacts/{contact_id}" },
  { name: "get_contact_by_reference", description: "Get a contact by reference_id. reference_id_type is required: zcrm_contact_id, zcrm_account_id or zcrm_vendor_id (needs the matching Zoho CRM sync).", path: "/contacts/reference/{reference_id}", filters: ["reference_id_type"] },
  { name: "list_contact_addresses", description: "List addresses across all contacts.", path: "/contacts/address" },
  { name: "get_contact_addresses", description: "Billing, shipping and additional addresses of a contact.", path: "/contacts/{contact_id}/address" },
  { name: "list_contact_comments", description: "Recent activity/comments on a contact.", path: "/contacts/{contact_id}/comments", paginated: true },
  { name: "get_contact_statement", description: "Statement for a contact.", path: "/contacts/{contact_id}/statements" },
  { name: "get_contact_statement_email", description: "Statement email content for a contact.", path: "/contacts/{contact_id}/statements/email", filters: ["start_date", "end_date"] },
  { name: "get_contact_email", description: "Email content for a contact.", path: "/contacts/{contact_id}/email" },
  { name: "list_contact_credit_refunds", description: "Credit note refunds of a contact.", path: "/contacts/{contact_id}/refunds", paginated: true },
  { name: "list_contact_payment_refunds", description: "Payment refunds of a contact.", path: "/contacts/{contact_id}/paymentrefunds" },
  { name: "get_contact_unused_retainer_payments", description: "Unused retainer payments of a contact.", path: "/contacts/{contact_id}/receivables/unusedretainerpayments", filters: ["currency_id"] },
  { name: "get_contact_unused_credits", description: "Unused credits of a contact.", path: "/contacts/{contact_id}/receivables/unusedcredits" },
  { name: "list_contact_bank_accounts", description: "Bank accounts of a contact.", path: "/contacts/{contact_id}/bankaccounts" },
  { name: "get_contact_bank_account", description: "One bank account of a contact.", path: "/contacts/{contact_id}/bankaccount/{bank_account_id}" },
  { name: "list_all_contact_bank_accounts", description: "Bank accounts of the contacts in contact_ids (comma-separated, required).", path: "/contacts/bankaccounts", filters: ["contact_ids"] },
  { name: "list_contact_cards", description: "Cards on file for a contact.", path: "/contacts/{contact_id}/cards" },
  { name: "get_contact_card", description: "One card on file for a contact.", path: "/contacts/{contact_id}/card/{card_id}" },
  { name: "get_contact_card_count", description: "Count of cards on file for the contacts in contact_ids (comma-separated, required).", path: "/contacts/cardcount", filters: ["contact_ids"] },
  { name: "list_card_recurring_invoices", description: "Auto-bill recurring invoices on a contact card.", path: "/contacts/{contact_id}/card/{card_id}/recurringinvoices" },
  { name: "list_all_contact_persons", description: "Contact persons across all contacts.", path: "/contacts/contactpersons" },
  { name: "list_contact_persons", description: "Contact persons of one contact.", path: "/contacts/{contact_id}/contactpersons", paginated: true },
  { name: "get_contact_person", description: "One contact person of a contact.", path: "/contacts/{contact_id}/contactpersons/{contact_person_id}" },
  { name: "get_contact_tax_info", description: "Tax information of a contact.", path: "/contacts/{contact_id}/taxinfo" },
  { name: "get_contact_income_and_expense", description: "Income and expense summary for a contact.", path: "/contacts/{contact_id}/incomeandexpense" },
  { name: "get_contact_profit_and_loss", description: "Profit and loss for a contact.", path: "/contacts/{contact_id}/profitandloss" },
  { name: "get_contact_inventory_summary", description: "Inventory summary for a contact.", path: "/contacts/{contact_id}/inventorysummary" },
  { name: "get_contact_opening_balances", description: "Opening balances of a contact. contact_type (customer or vendor) is required.", path: "/contacts/{contact_id}/openingbalances", filters: ["contact_type"] },

  // ---- estimates ----
  { name: "list_estimates", description: "List estimates (quotes).", path: "/estimates", paginated: true,
    filters: [...dates, "estimate_number", "reference_number", "customer_name", "total", "customer_id", "item_id", "item_name", "expiry_date", "last_modified_time", "status", "zcrm_potential_id", "location_ids", ...common] },
  { name: "get_estimate", description: "Get an estimate by estimate_id, including line items.", path: "/estimates/{estimate_id}" },
  { name: "get_estimate_email", description: "Email content for an estimate.", path: "/estimates/{estimate_id}/email", filters: ["email_template_id"] },
  { name: "list_estimate_templates", description: "List estimate templates.", path: "/estimates/templates" },
  { name: "list_estimate_comments", description: "Estimate history and comments.", path: "/estimates/{estimate_id}/comments" },

  // ---- sales orders / receipts / challans ----
  { name: "list_sales_orders", description: "List sales orders.", path: "/salesorders", paginated: true,
    filters: [...dates, "salesorder_number", "reference_number", "customer_name", "customer_id", "salesperson_id", "item_id", "item_name", "email", "total", "shipment_date", "status", "salesorder_ids", "last_modified_time", "zcrm_potential_id", "customview_id", "location_ids", ...common] },
  { name: "get_sales_order", description: "Get a sales order by salesorder_id, including line items.", path: "/salesorders/{salesorder_id}" },
  { name: "get_sales_order_email", description: "Email content for a sales order.", path: "/salesorders/{salesorder_id}/email", filters: ["email_template_id"] },
  { name: "list_sales_order_templates", description: "List sales order templates.", path: "/salesorders/templates" },
  { name: "list_sales_order_comments", description: "Sales order history and comments.", path: "/salesorders/{salesorder_id}/comments" },
  { name: "list_sales_receipts", description: "List sales receipts.", path: "/salesreceipts", paginated: true,
    filters: [...dates, "receipt_number", "item_name", "customer_id", "total", "filter_by", "sort_column"] },
  { name: "get_sales_receipt", description: "Get a sales receipt.", path: "/salesreceipts/{sales_receipt_id}" },
  { name: "list_delivery_challans", description: "List delivery challans.", path: "/deliverychallans", paginated: true, filters: ["customer_id", "status", "search_text", "filter_by", "sort_column", "sort_order"] },
  { name: "get_delivery_challan", description: "Get a delivery challan.", path: "/deliverychallans/{deliverychallan_id}" },
  { name: "list_delivery_challan_templates", description: "List delivery challan templates.", path: "/deliverychallans/templates" },

  // ---- invoices ----
  { name: "list_invoices", description: "List invoices. response_option 1-4 adds counts/sums of total and balance.", path: "/invoices", paginated: true,
    filters: [...dates, "invoice_number", "reference_number", "customer_name", "customer_id", "email", "recurring_invoice_id", "item_id", "item_name", "total", "balance", "due_date", "created_date", "last_modified_time", "status", "zcrm_potential_id", "response_option", ...common] },
  { name: "get_invoice", description: "Get an invoice by invoice_id, including line items.", path: "/invoices/{invoice_id}" },
  { name: "get_invoice_email", description: "Email content for an invoice.", path: "/invoices/{invoice_id}/email", filters: ["email_template_id"] },
  { name: "get_invoice_payment_reminder", description: "Payment reminder mail content for an invoice.", path: "/invoices/{invoice_id}/paymentreminder" },
  { name: "list_invoice_templates", description: "List invoice templates.", path: "/invoices/templates" },
  { name: "list_invoice_payments", description: "Payments applied to an invoice.", path: "/invoices/{invoice_id}/payments" },
  { name: "list_invoice_credits_applied", description: "Credits applied to an invoice.", path: "/invoices/{invoice_id}/creditsapplied" },
  { name: "get_invoice_document", description: "Metadata of an attachment on an invoice.", path: "/invoices/{invoice_id}/documents/{document_id}", fixed: { responseformat: "json" } },
  { name: "list_invoice_comments", description: "Invoice history and comments.", path: "/invoices/{invoice_id}/comments" },
  { name: "get_invoice_dashboard", description: "Invoice dashboard summary.", path: "/invoices/dashboard", filters: ["invoice_agent"] },
  { name: "get_invoice_custom_fields", description: "Custom fields of an invoice.", path: "/invoices/{invoice_id}/customfields" },
  { name: "get_invoice_tracking_details", description: "Batch/serial tracking details of an invoice.", path: "/invoices/{invoice_id}/advancedtrackingdetails" },
  { name: "get_invoice_sms", description: "SMS content for an invoice.", path: "/invoices/{invoice_id}/sms" },
  { name: "get_invoice_metadata", description: "A metadata value of an invoice.", path: "/invoices/{invoice_id}/metadata/{metadata_name}" },
  { name: "list_e_invoices", description: "E-invoices for the invoices in invoice_ids (comma-separated, required). Needs an edition with e-invoicing.", path: "/invoices/einvoice", filters: ["invoice_ids"] },
  { name: "get_e_invoice", description: "E-invoice JSON for an invoice.", path: "/invoices/{invoice_id}/einvoice" },
  { name: "list_customer_debit_notes", description: "List customer debit notes (served by the invoices endpoint).", path: "/invoices", paginated: true,
    fixed: { filter_by: "Type.DebitNote" }, filters: [...dates, "customer_name", "customer_id", "email", "total", "balance", "status", "search_text", "sort_column"] },
  { name: "list_recurring_invoices", description: "List recurring invoices.", path: "/recurringinvoices", paginated: true,
    filters: ["recurrence_name", "item_name", "customer_name", "customer_id", "item_id", "tax_id", "notes", "start_date", "end_date", "status", ...common] },
  { name: "get_recurring_invoice", description: "Get a recurring invoice.", path: "/recurringinvoices/{recurring_invoice_id}" },
  { name: "list_recurring_invoice_comments", description: "Recurring invoice history.", path: "/recurringinvoices/{recurring_invoice_id}/comments" },
  { name: "get_recurring_invoices_dashboard", description: "Recurring invoices dashboard.", path: "/recurringinvoices/dashboard" },
  { name: "list_recurring_invoice_children", description: "Invoices created from a recurring invoice.", path: "/recurringinvoices/{recurring_invoice_id}/invoices", filters: ["filter_by", "search_text", "sort_column"] },
  { name: "list_retainer_invoices", description: "List retainer invoices.", path: "/retainerinvoices", paginated: true, filters: ["filter_by", "sort_column", "sort_order"] },
  { name: "get_retainer_invoice", description: "Get a retainer invoice.", path: "/retainerinvoices/{retainerinvoice_id}" },
  { name: "get_retainer_invoice_email", description: "Email content for a retainer invoice.", path: "/retainerinvoices/{retainerinvoice_id}/email" },
  { name: "list_retainer_invoice_templates", description: "List retainer invoice templates.", path: "/retainerinvoices/templates" },
  { name: "list_retainer_invoice_comments", description: "Retainer invoice history.", path: "/retainerinvoices/{retainerinvoice_id}/comments" },

  // ---- credit notes ----
  { name: "list_credit_notes", description: "List customer credit notes.", path: "/creditnotes", paginated: true,
    filters: [...dates, "creditnote_number", "reference_number", "customer_name", "customer_id", "item_id", "item_name", "line_item_id", "tax_id", "total", "status", "last_modified_time", "location_ids", ...common] },
  { name: "get_credit_note", description: "Get a credit note by creditnote_id.", path: "/creditnotes/{creditnote_id}" },
  { name: "get_credit_note_email", description: "Email content for a credit note.", path: "/creditnotes/{creditnote_id}/email", filters: ["email_template_id"] },
  { name: "get_credit_note_mail_content", description: "Default mail content for a credit note.", path: "/creditnotes/{creditnote_id}/mailcontent" },
  { name: "get_credit_note_email_history", description: "Email history of a credit note.", path: "/creditnotes/{creditnote_id}/emailhistory" },
  { name: "list_credit_note_templates", description: "List credit note templates.", path: "/creditnotes/templates" },
  { name: "list_credit_note_invoices", description: "Invoices credited by a credit note.", path: "/creditnotes/{creditnote_id}/invoices" },
  { name: "list_credit_note_comments", description: "Credit note history and comments.", path: "/creditnotes/{creditnote_id}/comments" },
  { name: "list_all_credit_note_refunds", description: "Refunds across all credit notes.", path: "/creditnotes/refunds", paginated: true, filters: ["customer_id", "sort_column"] },
  { name: "list_credit_note_refunds", description: "Refunds of one credit note.", path: "/creditnotes/{creditnote_id}/refunds", paginated: true },
  { name: "get_credit_note_refund", description: "One refund of a credit note.", path: "/creditnotes/{creditnote_id}/refunds/{creditnote_refund_id}" },
  { name: "get_credit_note_refund_by_id", description: "A credit note refund by refund_id.", path: "/creditnotes/refunds/{refund_id}" },
  { name: "get_credit_note_document", description: "Metadata of an attachment on a credit note.", path: "/creditnotes/{creditnote_id}/documents/{document_id}", fixed: { responseformat: "json" } },
  { name: "get_credit_note_custom_fields", description: "Custom fields of a credit note.", path: "/creditnotes/{creditnote_id}/customfields" },
  { name: "list_credit_note_e_invoices", description: "E-invoices for the credit notes in creditnote_ids (comma-separated, required). Needs an edition with e-invoicing.", path: "/creditnotes/einvoice", filters: ["creditnote_ids"] },
  { name: "get_credit_note_e_invoice", description: "E-invoice JSON for a credit note.", path: "/creditnotes/{creditnote_id}/einvoice" },

  // ---- customer payments ----
  { name: "list_customer_payments", description: "List customer payments (money received).", path: "/customerpayments", paginated: true,
    filters: [...dates, "customer_name", "customer_id", "reference_number", "amount", "notes", "payment_mode", ...common] },
  { name: "get_customer_payment", description: "Get a customer payment by payment_id.", path: "/customerpayments/{payment_id}" },
  { name: "list_customer_payment_refunds", description: "Refunds of a customer payment.", path: "/customerpayments/{customer_payment_id}/refunds", paginated: true },
  { name: "get_customer_payment_refund", description: "One refund of a customer payment.", path: "/customerpayments/{customer_payment_id}/refunds/{refund_id}" },
];
